# Application name
spring.application.name=expense_tracker
spring.config.import=optional:file:.env[.properties]

# Live reload and automatic restart settings for development
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Global log level
logging.level.root=INFO


# More detailed logs for your package
logging.level.james.expense_tracker=DEBUG

# Console log pattern (single-line, readable)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

# Database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# JPA settings
# when the app starts, check if the database matches the entity mappings,
# but do not update or change anything
spring.jpa.hibernate.ddl-auto=validate

# JWT settings
jwt.secret=${JWT_SECRET}
jwt.access-expiration-ms=${JWT_ACCESS_EXP_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXP_MS}